services:
  backend:
    build:
      context: ../TradeIt-backend
      dockerfile: ../DockersReact-Node/TradeItBackend/Dockerfile
    volumes:
      - ../TradeIt-backend:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/TradeIt
      - PORT=9001
    expose:
      - "9001"
    networks:
      test:
        ipv4_address: 10.18.0.3

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      test:
        ipv4_address: 10.18.0.4

volumes:
  mongo-data:

networks:
  test:
    driver: bridge
    ipam:
      config:
        - subnet: 10.18.0.0/16
