services:
  frontend:
    build:
      context: ../TradeItMobile
      dockerfile: ../DockersReact-Node/TradeItMobile/Dockerfile
    volumes:
        - ../TradeItMobile:/app
        - /app/node_modules
    ports:
        - "19000:19000"  # puerto principal de expo
        - "19001:19001"  # WebSocket de desarrollo
        - "19002:19002"  # Interfaz web de metro bundler
    stdin_open: true
    tty: true
    environment:
      - HOST=0.0.0.0
    networks:
      test:
        ipv4_address: 10.18.0.2
  backend:
    build:
      context: ../TradeIt-backend
      dockerfile: ../DockersReact-Node/TradeItBackend/Dockerfile
    volumes:
      - ../TradeIt-backend:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/TradeIt
    expose:
      - "9001"
    networks:
      test:
        ipv4_address: 10.18.0.3

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      test:
        ipv4_address: 10.18.0.4

volumes:
  mongo-data:

networks:
  test:
    driver: bridge
    ipam:
      config:
        - subnet: 10.18.0.0/16
