services:
  frontend:
    build:
      context: /home/raul/Documents/GitProjects/TradeIt-frontend
      dockerfile: /home/raul/Documents/GitProjects/dockerfiles/DockersReact-Node/TradeItFrontend/Dockerfile
    volumes:
      - /home/raul/Documents/GitProjects/TradeIt-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
    - HOST=0.0.0.0
    networks:
      test:
        ipv4_address: 10.18.0.2

  backend:
    build:
      context: /home/raul/Documents/GitProjects/TradeIt-backend
      dockerfile: /home/raul/Documents/GitProjects/dockerfiles/DockersReact-Node/TradeItBackend/Dockerfile
    volumes:
      - /home/raul/Documents/GitProjects/TradeIt-backend:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/TradeIt
    expose:
      - "9001"
    networks:
      test:
        ipv4_address: 10.18.0.3

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      test:
        ipv4_address: 10.18.0.4

volumes:
  mongo-data:

networks:
  test:
    driver: bridge
    ipam:
      config:
        - subnet: 10.18.0.0/16
